name: Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    strategy:
      matrix:
        node-version: [14, 16, 17]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --immutable
      - run: yarn run build
      # Our fake git commit system doesn't work in GH jobs
      # - run: yarn run jest
      - run: yarn run lint
