name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: '0'

      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - uses: actions/setup-node@v3

      - name: Authenticate with Registry
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Packages
        run: yarn install --immutable

      - name: Build packages
        run: yarn run pack

      - name: Publish package
        run: yarn run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Packages
        run: yarn install --no-immutable

      - name: Setup git
        run: |
          git config --global user.email "lumos@oriflame.com"
          git config --global user.name "Lumos Bot"

      - name: Push yarn lock
        run: |
          git commit -am 'internal: Regenerate yarn lock. [ci skip]' --no-verify
          git push
